version: "3"
services:
  
  backend:
    build: ./backend
    image: backend_labsadmin_dev
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0:7125"
    volumes:
      - ./backend:/labs/
    ports:
       - "7125:7125"

