# Generated by Django 3.2 on 2021-10-27 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20210914_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_petition', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(blank=True, default='', max_length=20)),
                ('day_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.daypetition')),
            ],
        ),
        migrations.CreateModel(
            name='LabPetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_petition', models.CharField(default='', max_length=50)),
                ('email_petition', models.CharField(default='', max_length=100)),
                ('nrc_petition', models.CharField(blank=True, default='', max_length=10)),
                ('cant_pc_petition', models.IntegerField(default='')),
                ('day_start_petition', models.DateField(null=True)),
                ('day_finish_petition', models.DateField(null=True)),
                ('time_start_petition', models.TimeField(null=True)),
                ('time_finish_petition', models.TimeField(null=True)),
                ('memo_petition', models.CharField(default='', max_length=250)),
                ('status_petition', models.CharField(blank=True, choices=[('P', 'Pendiente'), ('A', 'Aceptado'), ('R', 'Rechazado')], default='P', max_length=1)),
                ('campus_petition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campus')),
                ('day_petition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.daypetition')),
                ('laboratory_petition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.TimeField(null=True)),
                ('hour_finish', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.event')),
                ('lab_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.labpetition')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='module_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.module'),
        ),
    ]
