# Generated by Django 3.2 on 2021-10-19 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210914_0159'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='lab_petition',
        ),
        migrations.AddField(
            model_name='petition',
            name='laboratory_petition',
            field=models.CharField(default='vacio', max_length=10),
        ),
        migrations.AddField(
            model_name='petition',
            name='license',
            field=models.CharField(choices=[(0, '')], default='vacio', max_length=50),
        ),
        migrations.AddField(
            model_name='petition',
            name='memo',
            field=models.CharField(default='vacio', max_length=250),
        ),
        migrations.AddField(
            model_name='petition',
            name='status',
            field=models.CharField(default='vacio', max_length=20),
        ),
        migrations.AddField(
            model_name='petition',
            name='time_finish',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='time_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='email_petition',
            field=models.CharField(default='vacio', max_length=100),
        ),
        migrations.AlterField(
            model_name='petition',
            name='name_petition',
            field=models.CharField(default='vacio', max_length=100),
        ),
        migrations.AlterField(
            model_name='petition',
            name='nrc_petition',
            field=models.CharField(default='vacio', max_length=10),
        ),
        migrations.AlterField(
            model_name='petition',
            name='pc_petition',
            field=models.CharField(default='vacio', max_length=3),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workstation')),
            ],
        ),
    ]
