# Generated by Django 3.2 on 2021-10-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpetition',
            name='email_petition',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='labpetition',
            name='memo_petition',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
