# Generated by Django 3.2 on 2021-10-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20211029_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpetition',
            name='email_petition',
            field=models.CharField(default='', max_length=150),
        ),
    ]
