# Generated by Django 3.2 on 2021-10-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20211019_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='email_petition',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='petition',
            name='laboratory_petition',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='petition',
            name='license',
            field=models.CharField(choices=[(0, '')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='petition',
            name='memo',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='petition',
            name='name_petition',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='petition',
            name='nrc_petition',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='petition',
            name='pc_petition',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='petition',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='petition',
            name='time_finish',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
