# Generated by Django 3.2 on 2021-10-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210914_0159'),
        ('schedules', '0003_auto_20211019_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='workstation',
        ),
        migrations.AddField(
            model_name='schedule',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.petition'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room'),
        ),
    ]
