# Generated by Django 3.2 on 2021-10-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210914_0159'),
        ('schedules', '0004_auto_20211020_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='room',
        ),
        migrations.AddField(
            model_name='petition',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campus'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='laboratory_petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room'),
        ),
    ]
