# Generated by Django 3.2 on 2021-10-20 21:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20211020_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 21, 45, 57, 480721, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 20, 21, 45, 57, 481495, tzinfo=utc), null=True),
        ),
    ]
