# Generated by Django 3.2 on 2021-10-20 21:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210914_0159'),
        ('schedules', '0007_auto_20211020_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='campus_petition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campus'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='license',
            field=models.CharField(blank=True, choices=[(1, 'EJ'), (2, 'EJ2')], default='Ninguna', max_length=20),
        ),
        migrations.AlterField(
            model_name='petition',
            name='nrc_petition',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='petition',
            name='status',
            field=models.CharField(blank=True, default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='petition',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 21, 58, 32, 2377, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 20, 21, 58, 32, 3034, tzinfo=utc), null=True),
        ),
    ]
