# Generated by Django 3.2 on 2021-10-20 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20211020_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='day_finish',
            field=models.DateField(default=datetime.datetime(2021, 10, 20, 22, 8, 51, 693491, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='day_start',
            field=models.DateField(default=datetime.datetime(2021, 10, 20, 22, 8, 51, 693452, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='license',
            field=models.CharField(blank=True, choices=[(1, 'EJ'), (2, 'EJ2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='petition',
            name='time_finish',
            field=models.TimeField(default=datetime.datetime(2021, 10, 20, 22, 8, 51, 693503, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='time_start',
            field=models.TimeField(default=datetime.datetime(2021, 10, 20, 22, 8, 51, 693475, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 20, 22, 8, 51, 694124, tzinfo=utc), null=True),
        ),
    ]
