# Generated by Django 3.2 on 2021-10-21 01:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20211020_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='license',
            new_name='license_petition',
        ),
        migrations.RenameField(
            model_name='petition',
            old_name='memo',
            new_name='memo_petition',
        ),
        migrations.RenameField(
            model_name='petition',
            old_name='status',
            new_name='status_petition',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='day_finish',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='day_start',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='time_finish',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='time_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.AddField(
            model_name='petition',
            name='active_petition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petition',
            name='day_finish_petition',
            field=models.DateField(default=datetime.datetime(2021, 10, 21, 1, 36, 39, 113152, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='day_petition',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='petition',
            name='day_start_petition',
            field=models.DateField(default=datetime.datetime(2021, 10, 21, 1, 36, 39, 113113, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='time_finish_petition',
            field=models.TimeField(default=datetime.datetime(2021, 10, 21, 1, 36, 39, 113165, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='time_start_petition',
            field=models.TimeField(default=datetime.datetime(2021, 10, 21, 1, 36, 39, 113136, tzinfo=utc), null=True),
        ),
    ]
